### ISSUE TITLE
xAOD migration jet

### ISSUE THREAD

**Issue by ataffard** [susynt/SusyCommon#26]
10/30/14:
Completed:
- isBadVeryLoose
- detEta (detector eta)
- mv1 (btagging result)
- sv1plusip3d (btagging result => also needed change in SusyNt)
- bch_corr_jet
- bch_corr_cell

Need clarification/ follow-up:
- JVF returns one value per vertex in the event. We need a robust way of picking the value associated to the primary vertex, I need to look around.
- Truth labeling and matching is not quite clear to me. Any one know anything on that front?
- Some (if not most/all) of the b-tagging weights seem to be obsolete, this part needs clean-up. I think 8 TeV DC 14 samples only have meaningful SV1plusIP3D, but no MV1 result
- BCH cleaning will be obsolete (?) so needs clean-up after confirmation 
- Also I'm not 100% sure about the MET weights, these will be obsolete for rel 20 but not for rel 19.

**Comment by amete** [comment]
Just to note that I'll look into this.

-s
