### ISSUE TITLE
xAOD migration : electron & sytematics

### ISSUE THREAD

**Issue by ataffard** [susynt/SusyCommon#31]
@gerbaudo , @amete , @suneetu 

    - Completed	 
	Instantiate multiple SUSYToolsObj for each electron flavor.
	Added LLH electron type and SF
	Added Pho isolation
	Added function to get PV based on VertexType==1 as recommended here
		https://twiki.cern.ch/twiki/bin/viewauth/AtlasProtected/InDetTrackingPerformanceGuidelines
	Ready to start adding systematics
     - AOB: anything that you noticed and you think needs fixing.
	SUSYTools: GetSF function don’t return the error 
	In SusyNt::Particle we were used to store the idx of the d3pd lepton  // to remove ?

**Comment by mikeflowerdew** [comment]
This is an old issue, but from the title it's nominally relevant. It seems that the electron eta cut in SusyCommon ([here](https://github.com/susynt/SusyCommon/blob/master/Root/XaodAnalysis.cxx#L1033)) is applied to the total electron four-momentum, while the [SUSY recommendation](https://twiki.cern.ch/twiki/bin/view/AtlasProtected/SusyObjectDefinitionsr2013TeV#Electrons) is to apply this cut to the cluster. @srmaschek noticed a tiny difference in cutflow wrt xAOD analysers, and we suspect this is the cause.
