### ISSUE TITLE
xAOD migration: systematics

### ISSUE THREAD

**Issue by ataffard** [susynt/SusyCommon#37]
@gerbaudo @amete @suneetu @ataffard

I have added the systematics (kinematic variations) to the susyNt on the xaod-syst branch.
Ele, mu, tau are done.
Jet is sort of done, but I run into a problem trying to use arrays in the jet class (i got fed up typing all these systematic variations). 
It seems not to like storing 2D arrays when booking the TTree at runtime. May be the D3PDReader cannot handle this ? Any idea how to fix this ?

I've touch lots of files to get all this in... would be good to get this merged before others touch a lot of the code.

I was not able to find an event when a object had to be added when doing the sys variation... Code should work, but it's untested.

**Comment by amete** [comment]
Hi,

So the follow-up for my discussion w/ @ataffard. Can people comment where we are in terms of finalizing the systematics? @gerbaudo @suneetu @dantrim Looking at my note, I see that we need to implement some of the b-tagging systematics etc. What are the key missing ones? Also today there'll be a discussion in the introduction slides for the BG forum about the JES, and the effort to minimize the number of NPs. It'll be good if we can take a look at this, and other missing issues. 

-s
