### ISSUE TITLE
xAOD migration: MET

### ISSUE THREAD

**Issue by ataffard** [susynt/SusyCommon#39]
@gerbaudo @amete 

There is a bug in the current code:
 `metOut->phi = (*met_it)->phi()*MeV2GeV;`
heuh?!?

For the refTerm, we need to add the `refTau`.
For these we currently store `Et, Ex, Ey, sumEt`... That's a waste of a float.
I would propose to store `Et,Phi` and return a TLV using the `lv()` function where no argument would return the MET (as now) and argument "RefEle" etc... would return the corresponding term.
We could also add a similar function for the `sumEt`.

I also email TJ/Ximo a bunch of questions... 
Email titled "xAOD/Met related questions"
(this is timely and I got tired of waiting for S to send it)

**Comment by amete** [comment]
Hi guys,

I had a chat w/ @ataffard yesterday, and we wanted to follow-up on the xAOD related stuff and see where we are. For what concerns the MET, we have a few open issues such as addition of track MET etc. (I see there is another ticket on that). I think @suneetu was looking into this. Can we revive this, and tie the loose ends, please? Let me know.

-s
