### ISSUE TITLE
error on sf electron

### ISSUE THREAD

**Issue by gerbaudo** [susynt/SusyCommon#47]
Needs to be retrieved from SUSYTools

**Comment by amete** [comment]
Hi @gerbaudo ,

I have an initial implementation of this here:

https://github.com/gerbaudo/SusyCommon/blob/xaod_muonSF/Root/SusyNtMaker.cxx#L422

This goes in parallel w/ the muon scale factors, so I can also tackle this one.

Best,
Serhan
