### ISSUE TITLE
get rid of stream check on data

### ISSUE THREAD

**Issue by gerbaudo** [susynt/SusyCommon#68]
Not available anymore for run2

**Comment by dantrim** [comment]
I have added the checks for the PhysicsMain stream "Main" that data15 will be using in the DataStream enum in SusyDefs as well as the checks that take place in XaodAnalysis.cxx. I have confirmed that we can run on a DAOD_SUSY9 sample (p2361).

**Comment by gerbaudo** [comment]
fixed in susynt/SusyNtuple@7b4cec013806a53f86307ad8d2c2a2d50ecae779
