### ISSUE TITLE
Add LHE3 weights

### ISSUE THREAD

**Issue by dantrim** [susynt/SusyCommon#84]
These are PDF weights, no? @asoffa I will assign this to you as you added to [asana](https://app.asana.com/0/185534950160524/185534950160549). Start this from a new branch and submit the pull request from there to master. Does anything need to be added to SusyNtuple/Event?

**Comment by dantrim** [comment]
@asoffa @amete this never converged, right?

**Comment by asoffa** [comment]
I'm closing this for now. The MC weights (including the LHE3 weights if they are available in the dataset being processed) were added in https://github.com/susynt/SusyCommon/commit/7d4ef6ea69f60ef073d2e30e724875f9c61fd58d. Currently, only the weights themselves can be obtained from the most recent DAOD_SUSY2 productions. The weight names are obtained using an ad-hoc, sample-specific procedure [1] *after* the SusyNt tree is made. (None of the current productions have the needed `xAOD::TruthMetaData` or `HepMCWeightNames` for using one of the other options described in [1].) This can be reopened in the future if a new DAOD_SUSY2 production has the needed meta data for obtaining the weight names directly.

[1] https://twiki.cern.ch/twiki/bin/viewauth/AtlasProtected/LHE3EventWeights#Interim_solution_for_use_in_case
