### ISSUE TITLE
Add derivation type awareness

### ISSUE THREAD

**Issue by amete** [susynt/SusyCommon#87]
So if we end up running over different derivation types (i.e. Higgs etc.) we need a handle on the derivation type so that we won't try to retrieve information that is specific to a given derivation. One can check if the decoration is available or not but I believe this way is more instructive. A prototype is implemented on the branch 9c07972.

**Comment by amete** [comment]
@dantrim, can we collect this in n0229?

**Comment by dantrim** [comment]
@amete this is done [here](https://github.com/susynt/SusyCommon/blob/master/Root/XaodAnalysis.cxx#L2053), right? If so, I'll close this...

**Comment by amete** [comment]
Yeah, we use it [here](https://github.com/susynt/SusyCommon/blob/master/Root/SusyNtMaker.cxx#L366) and [here](https://github.com/susynt/SusyCommon/blob/master/Root/SusyNtMaker.cxx#L633).

**Comment by dantrim** [comment]
cool, I'll close this. thanks @amete
